### ISSUE TITLE
[Documentation] Move Examples to a Directory

### ISSUE THREAD

**Issue by vaguecoder** [vaguecoder/gorilla-mux#14]
## What?
Currently, all examples are on [README.md][1] making scroll forever. Need to move them to a directory `examples/` with respective document names and hyperlinks, except for [installation][2] and [examples][3] (which only has 3 code blocks).

## Why?
[README.md][1] too lengthy.

## Additional Context
NA

## Ownership of Contribution
If the triage is approved,
- [ ] I wish to submit the PR myself.
- [x] I wish to submit the PR. But if someone is willing to do it, go ahead.
- [ ] I don't know how to fix this or make these changes. I wish others to pick this up for me.

[1]: https://github.com/vaguecoder/gorilla-mux/blob/master/README.md
[2]: https://github.com/vaguecoder/gorilla-mux/blob/master/README.md#install
[3]: https://github.com/vaguecoder/gorilla-mux/blob/master/README.md#examples

**Comment by Rishav1707** [comment]
Shall I work on this issue? @vaguecoder

**Comment by vaguecoder** [comment]
Can you please pick this up post the completion of #6 which might conflict? I'll assign this to you.

@Tanryberdi FYI.

**Comment by vaguecoder** [comment]
Good job @Rishav1707 Thanks for the contribution.
