### ISSUE TITLE
[Bug] `ioutil` is deprecated

### ISSUE THREAD

**Issue by vaguecoder** [vaguecoder/gorilla-mux#17]
## Describe the Bug
[ioutil][1] is deprecated. Replace all occurrences of `ioutil` with `io` or `os` w.r.t. the functions in use.

## To Reproduce
NA

## Additional Context
NA

## Ownership of Contribution
If the triage is approved,
- [ ] I wish to submit the PR myself.
- [x] I wish to submit the PR. But if someone is willing to do it, go ahead.
- [ ] I don't know how to fix this or make these changes. I wish others to pick this up for me.

[1]: https://pkg.go.dev/io/ioutil

**Comment by tanryberdi** [comment]
@assign
