### ISSUE TITLE
Upgrade go version to latest

### ISSUE THREAD

**Issue by vaguecoder** [vaguecoder/gorilla-mux#3]
Upgrade the go version to the latest in
1. Go modules
2. ~Circle CI~ GitHub Actions

**Comment by tanryberdi** [comment]
Hey @vaguecoder 
I want to take this issue, by the way, could you please add one more issue to create `.gitignore` file? 🙏

**Comment by vaguecoder** [comment]
Hey @tanryberdi, thanks for checking on this. Please go ahead and pick this (issue) up. CircleCI is not currently active on this but let's keep things consistent.

About `.gitignore`, I see the upstream [gorilla/mux][1] hasn't left any ignorable files. So let's create it when required.

About typos and doc corrections, feel free to open an issue with the bug-report template. I've added the templates to the project.

[1]: https://github.com/gorilla/mux

**Comment by tanryberdi** [comment]
@vaguecoder you merged PR for issue#2, but I could not `git pull` from master branch, what was the problem for that? wdyt?
