### ISSUE TITLE
Add `.golangci.yaml`

### ISSUE THREAD

**Issue by vaguecoder** [vaguecoder/gorilla-mux#4]
Add [golangci-lint][1] to the project and add the target to `Makefile`

[1]: https://github.com/golangci/golangci-lint

**Comment by tanryberdi** [comment]
@assign

**Comment by vaguecoder** [comment]
@tanryberdi To explain a bit on this, we need to configure `.golangci.yaml` to use some default + commonly used linters from [golangci-lint][1]. Try not to exclude any path unless necessary (and for specific linters).

[1]: https://github.com/golangci/golangci-lint

**Comment by vaguecoder** [comment]
Thanks @tanryberdi
